### ISSUE TITLE
About implementation of MMD

### ISSUE THREAD

**Issue by umgupta** [rampasek/DrVAE#1]
I have been trying to wrap my head around computing MMD part in VFAE and to me, it seems to me that approximating RBF kernel using random features does not give same results as RBF kernel for any bandwidth (or gamma) as is used in the paper. 

I tried to use your code for `mmd_objective` and did some test with standard Gaussian distributions and get different results. 

```
p = torch.randn((320,10))
q = 10 + torch.randn((320,10))
for bw in [.02, .2, 1., 2, 20]:
    a = mmd_objective(p,q, kernel="rbf", bandwidths=[bw])
    # since bandwidth is hardcoded to 2 in the mmd_objective, I had to call it the way below
    b = torch.sqrt(mmd_fourier(p,q, bandwidth=bw))
    print(f"bw : {bw}, rbf: {a}, fourier: {b}")
```

The result is 

```
bw : 0.02, rbf: 0.8016996383666992, fourier: 0.07742945104837418
bw : 0.2, rbf: 0.09800146520137787, fourier: 0.10620037466287613
bw : 1.0, rbf: 0.07907181978225708, fourier: 0.6043815612792969
bw : 2, rbf: 0.07905713468790054, fourier: 0.8595293760299683
bw : 20, rbf: 0.07905694097280502, fourier: 1.326660394668579
```
So I want to confirm what should be the typical value of gamma for the random features case and RBF kernel that works? It seems that VFAE paper did not clearly mention it either

**Comment by rampasek** [comment]
Hi @umgupta! The gamma in RBF kernel K(x,y) = \exp(-\gamma * ||x-y||^2) is different from the gamma in the random kitchen sinks MMD estimator. They don't mean the same thing.

1.  \gamma in RBF kenel:

When using actual RBF kernel MMD, there is no one \gamma that would be suitable for all datasets. See Zellinger et al. (ICLR 2017, ﻿http://arxiv.org/abs/1702.08811) where in the Experiments section they say that you need to find a suitable \gamma in cross-validation otherwise the regularization is unlikely to work (note that in this paper they actually call this kernel width parameter \beta instead of \gamma).


2. \gamma in MMD estimator:

Botros & Tomczak in their paper ﻿http://arxiv.org/abs/1806.09918 say (near eq.33) to use \gamma=2*M where M is the dimensionality of the input (i.e. 10 in your example) in case of the MMD approximation via random Fourier features.

The MMD objective code in this repo is adapted from Louizos et al. original VFAE code, but in the paper this repo is related to, I didn't end up using any MMD regularization.

**Comment by rampasek** [comment]
I run the MMD estimators also on the classic Boston housing data set, there the choice of \gamma seems to make a lot less difference.
https://colab.research.google.com/drive/1marMUULfcEt37IJma_0QEQxW-ya9mWRs

**Comment by umgupta** [comment]
Thanks for the reply, 
> "The gamma in RBF kernel K(x,y) = \exp(-\gamma * ||x-y||^2) is different from the gamma in the random kitchen sinks MMD estimator." 

Yes, the [original paper ](https://arxiv.org/pdf/1405.2664.pdf) has K(0) constant term and it was not clear to me, how that is computed. I looked into original code or FastMMD and realized it is something that can't be set independent of batch (or data). I don't remember the exact form. 

 The VFAE paper used \gamma for both and hence caused the confusion. Thanks for the other papers you pointed to. 

Thanks for the colab notebook. It seems there are some range of \gamma for which the results are not that sensitive and it depends on data. For example: I just tried to evaluate the MMD for other gammas and you can see variations (difference between RBF and fourier for same \gamma).

**Comment by umgupta** [comment]
I am sorry, I think I made mistakes in my previous comment, therefore I deleted it. Indeed there is a relation between the \sigma or \gamma used in FastMMD and RBF kernel. Actually, for the same \sigma, they should be approximately equal. VFAE paper probably has some error. 

What \gamma should be used can be a hyper-parameter decided by validation and I understood that, but I think my problem was that for same \sigma or \gamma both should be approximately equal as with kitchen sinks we are trying to approximate the RBF kernel MMD. 

I looked through the code of FastMMD and figured out the relations that I have summarized in this [gist](https://gist.github.com/umgupta/8306125b584ddf38b0f2401c1c9cadce).

Thanks for addressing this query and I hope it is ok to convert the colab notebook that you had shared into a gist.

**Comment by rampasek** [comment]
Thank you for the gist and figuring out the relationship between \sigma in RBF and \gamma in FastMMD!

I've looked into why in VFAE they set the \gamma to 2M. They use "median heuristic", a popular heuristic for selection of a kernel bandwidth in many applications. The heuristic is to set \sigma = \sqrt{H / 2} where H is the median square distance among samples of the dataset. Theory on justification of it is in https://arxiv.org/abs/1707.07269. In case of VFAE, the two posterior  distributions that are compared are M-dimensional gaussians with diagonal covariance matrices. If you assumed them to have equal mean and unit variance, then the expected square distance is 2*M. This leads to setting \sigma = \sqrt(M) as a good heuristic.
